# @package _global_.model
type: temporal_unet_dilated   # ← maps to TemporalUNetDilated

# --- temporal front‑end ---
time_hidden: 64              # channels in ConvLSTM hidden state

# --- U‑Net path ---
unet_init: 64                # first encoder level channels
depth: 4                     # encoder/decoder depth
dilation: 2                  # dilation factor used in dilated blocks

# --- regularization ---
dropout_rate: 0.2
