# @package _global_.model
type: temporal_cnn          # ← maps to TemporalCNN

# --- architecture hyper‑params ---
hidden_channels: 256         # channels inside ConvLSTM / feature extractor
depth: 2                     # number of stacked ConvLSTM cells
dropout_rate: 0.0

# (Nothing to set for kernel_size etc.; TemporalCNN fixes its own 3×3 convs.)
